#!/bin/bash -e

trap "cleartmpdir" SIGHUP SIGINT SIGQUIT SIGTERM

cleartmpdir() {
	rm -fr $VENOMISODIR
}

die() {
	echo "!! Error occurs !!"
	cleartmpdir
	exit 1
}

msg() {
	echo ":: $@"
}
					
prepareisolinux() {
	msg "preparing isolinux files"
	mkdir -p $VENOMISO/{filesystem,isolinux,boot}
	cp $ISOLINUXDIR/* $VENOMISO/isolinux
	echo "$DISTRONAME" > $VENOMISO/isolinux/venomlive
	cp $VENOMROOTSFS $VENOMISO/filesystem/root.sfs
	[ -d $OVERLAYDIR ] && cp -aR $OVERLAYDIR $VENOMISO
}

build_iso() {
	prepareisolinux
	prepare_bootfiles
	rm -f $OUTPUT
	msg "making iso"
	xorriso -as mkisofs \
		-r -J -joliet-long \
		-l -cache-inodes \
		-isohybrid-mbr $CWD/isolinux/isohdpfx.bin \
		-partition_offset 16 \
		-A "$LABEL" \
		-V "$LABEL" \
		-b isolinux/isolinux.bin \
		-c isolinux/boot.cat \
		-no-emul-boot \
		-boot-load-size 4 \
		-boot-info-table \
		-o $OUTPUT \
		$VENOMISO
}

prepare_bootfiles() {
	# kernel
	if [ $KERNEL ]; then
		if [ -f $KERNEL ]; then
			msg "copying kernel..."
			cp $KERNEL $VENOMISO/boot/vmlinuz
		else
			msg "kernel '$KERNEL' not found"
			exit 1
		fi
	else
		if [ -f $VENOMROOTFS/boot/vmlinuz-venom ]; then
			msg "copying kernel..."
			cp $VENOMROOTFS/boot/vmlinuz-venom $VENOMISO/boot/vmlinuz
		else
			msg "kernel (vmlinuz-venom) not exist!"
			exit 1
		fi
	fi

	# initrd
	if [ $INITRD ]; then
		if [ -f $INITRD ]; then
			msg "copying initramfs..."
			cp $INITRD $VENOMISO/boot/initrd
		else
			msg "initramfs '$INITRD' not found"
			exit 1
		fi
	else
		if [ -f $VENOMROOTFS/boot/initrd-venom.img ]; then
			msg "copying initramfs..."
			cp $VENOMROOTFS/boot/initrd-venom.img $VENOMISO/boot/initrd
		else
			msg "initramfs image (initrd) not exist!"
			exit 1
		fi
	fi
}

extract_rootfs() {
	if [ ! -f $ROOTFS ]; then
		msg "ERROR: venom rootfs not exist."
		exit 1
	fi
	mkdir -p $VENOMROOTFS
	msg "extract $ROOTFS"
	tar xJpf $ROOTFS -C $VENOMROOTFS
	if [ $? != 0 ]; then
		msg "ERROR: error extracting $ROOTFS."
		exit 1
	fi
}

make_rootsfs() {
	msg "making root.sfs"
	rm -f $CWD/root.sfs
	mksquashfs $VENOMROOTFS $VENOMROOTSFS \
		-b 1048576 -comp xz -Xdict-size 100% \
		-e $VENOMROOTFS/var/cache/scratchpkg/sources/* \
		-e $VENOMROOTFS/var/cache/scratchpkg/packages/* \
		-e $VENOMROOTFS/tmp/*
}

main() {
	parseopt "$@"
	
	cleartmpdir
	
	if [ "$SRCTYPE" = "image" ]; then
		ROOTFS=$SRC
		extract_rootfs
		#chroot_run scratch sync
		#chroot_run scratch sysup --no-confirm
		make_rootsfs
	elif [ "$SRCTYPE" = "dir" ]; then
		VENOMROOTFS=$SRC
		#chroot_run scratch sync
		#chroot_run scratch sysup --no-confirm
		if [ ! -f $VENOMROOTFS/usr/bin/mkinitramfs ]; then
			msg "ERROR: mkinitramfs is not installed for venom rootdir"
			exit 1
		fi
		if [ -f $VENOMROOTFS/boot/vmlinuz-venom ]; then
			kernver=$(file $VENOMROOTFS/boot/vmlinuz-venom | cut -d ' ' -f9)
		else
			msg "ERROR: kernel not found in venom rootdir directory"
			exit 1
		fi
		chroot_run mkinitramfs -k $kernver -o /boot/initrd-venom.img || die
		make_rootsfs
	elif [ "$SRCTYPE" = "sfs" ]; then
		VENOMROOTSFS=$SRC
		mkdir -p $VENOMROOTFS
		unsquashfs -f -d $VENOMROOTFS $VENOMROOTSFS /boot/vmlinuz-venom /boot/initrd-venom.img || die
	else
		echo "ERROR: source is not set."
		exit 1
	fi
	build_iso
	cleartmpdir
}

chroot_run() {
	mount_pseudofs
	chroot $VENOMROOTFS $@
	umount_pseudofs
}

mount_pseudofs() {
	mount --bind /dev $VENOMROOTFS/dev
	mount -t devpts devpts $VENOMROOTFS/dev/pts -o gid=5,mode=620
	mount -t proc proc $VENOMROOTFS/proc
	mount -t sysfs sysfs $VENOMROOTFS/sys
	mount -t tmpfs tmpfs $VENOMROOTFS/run
}

umount_pseudofs() {
	umount $VENOMROOTFS/dev/pts
	umount $VENOMROOTFS/dev
	umount $VENOMROOTFS/run
	umount $VENOMROOTFS/proc
	umount $VENOMROOTFS/sys
}

parseopt() {
	while [ "$1" ]; do
		case $1 in
			-o|--output)	if [ ! $2 ]; then
								echo "ERROR: option '$1' requires an argument."
								exit 1
							fi
							OUTPUT=$2
							shift ;;
			-i|--initrd)	if [ ! $2 ]; then
								echo "ERROR: option '$1' requires an argument."
								exit 1
							fi
							INITRD=$2
							shift ;;
			-k|--kernel)	if [ ! $2 ]; then
								echo "ERROR: option '$1' requires an argument."
								exit 1
							fi
							KERNEL=$2
							shift ;;
				*)			if [ "$SRC" ]; then
								echo "ERROR: invalid option '$1'"
								exit 1
							fi
							case $1 in
								*.txz) SRCTYPE=image ;;
								*.sfs) SRCTYPE=sfs ;;
								*)     SRCTYPE=dir ;;
							esac
							SRC=$1 ;;
		esac
		shift
	done
}

DISTRONAME="Venom"
CWD=$(pwd)
ISOLINUXDIR=$CWD/isolinux
OVERLAYDIR=$CWD/virootfs
DATE=$(date +"%Y%m%d")

VENOMISODIR=/tmp/venomiso
VENOMROOTFS=$VENOMISODIR/venom-rootfs
VENOMISO=$VENOMISODIR/venom-iso
VENOMROOTSFS=$CWD/root.sfs

LABEL=VenomLinuxLive
OUTPUT=venom-x86_64-$DATE.iso

main "$@"

exit 0
