#!/bin/bash -e

interrupted() {
	die "Abort by user."
}

cleanup() {
	[ "$cleanvenomsrc" = 1 ] && rm -fr $VENOMSRC
	rm -fr $WDIR
}

die() {
	[ "$@" ] && printerror $@
	umountbind_cache
	umount_pseudofs
	cleanup
	exit 1
}

printstep() {
	echo -e "\e[0;36m::\e[0m $@"
	echo -en "\033]0;$@\a"
}

printerror() {
	echo -e "\e[0;31mERROR:\e[0m $@"
}

chroot_run() {
	mount_pseudofs
	cp -L /etc/resolv.conf $VENOMSRC/etc/
	chroot $VENOMSRC $@
	retval=$?
	umount_pseudofs
	return $retval
}

mount_pseudofs() {
	mount --bind /dev $VENOMSRC/dev
	mount -t devpts devpts $VENOMSRC/dev/pts -o gid=5,mode=620
	mount -t proc proc $VENOMSRC/proc
	mount -t sysfs sysfs $VENOMSRC/sys
	mount -t tmpfs tmpfs $VENOMSRC/run
}

umount_pseudofs() {
	umount $VENOMSRC/dev/pts &>/dev/null
	umount $VENOMSRC/dev &>/dev/null
	umount $VENOMSRC/run &>/dev/null
	umount $VENOMSRC/proc &>/dev/null
	umount $VENOMSRC/sys &>/dev/null
}

mountbind_cache() {
	# mount bind cachedir
	mkdir -p $SRC_CACHE $PKG_CACHE
	mount --bind $SRC_CACHE $VENOMSRC/var/cache/scratchpkg/sources
	mount --bind $PKG_CACHE $VENOMSRC/var/cache/scratchpkg/packages
}

umountbind_cache() {
	# umount binded cachedir
	umount $VENOMSRC/var/cache/scratchpkg/sources &>/dev/null
	umount $VENOMSRC/var/cache/scratchpkg/packages &>/dev/null
}

fetch() {
	local filename
	filename=$(basename $ROOTFSURL)
	rm -f $filename
	if [ -f $filename.part ]; then
		wget -c --output-document=$filename.part $ROOTFSURL
	else
		wget --output-document=$filename.part $ROOTFSURL
	fi
	if [ $? != 0 ]; then
		return 1
	else
		mv $filename.part $filename
	fi
}

usage() {
	cat << EOF
Usage:
  $(basename $0) [options] <venom source>
  
Options:
  -p <path>           set packages cache directory
  -s <path>           set sources cache directory
  -P <pkg1 pkgN ...>  package to install into iso
  -i <initrd>         use custom initrd
  -k <kernel>         use custom kernel
  -o <name.iso>       output name for iso
  -c <file.preset>    use preset file
  -h                  show this help msg
  
Note:
  'venom source' should be a rootfs directory or rootfs tarball image
  if not define, it will download prebuilt one
  
EOF
}

checkinput() {
	if [ -z $1 ] || [[ $1 = -* ]]; then
		echo "this option need argument"
		exit 2
	fi
}

parseopt() {
	while [ "$1" ]; do
		case $1 in
			-p) checkinput $2
				PKG_CACHE=$2
				shift 2;;
			-s) checkinput $2
				SRC_CACHE=$2
				shift 2;;
			-i) checkinput $2
				INITRD_FILE=$2
				shift 2;;
			-k) checkinput $2
				KERNEL_FILE=$2
				shift 2;;
			-o) checkinput $2
				OUTPUT=$2
				shift 2;;
			-c) checkinput $2
				PRESET=$2
				shift 2;;
			-r) REVDEP="1"
				shift 1;;
			-P) checkinput $2
				while [ "$2" ]; do
					case $2 in
						-*) break ;;
						*) [ -z "$ADD_PKGS" ] && ADD_PKGS="$2" || ADD_PKGS="$ADD_PKGS $2"
					esac
					shift
				done
				shift ;;
			-h) usage; exit 0;;
			*)  VENOM=$1
				shift;;
		esac
	done
}

CWD=$PWD
WDIR=/tmp/venomiso
ISOLINUXDIR=$CWD/isolinux
DISTRONAME="Venom Linux"
LABEL=VenomLive
REQ_PKGS="dialog squashfs-tools"
VENOMSRC=/tmp/venomrootfs
ROOTFSURL="https://sourceforge.net/projects/venomlinux/files/venom-rootfs.txz"

isolinux_files="chain.c32 isolinux.bin ldlinux.c32 libutil.c32 reboot.c32 vesamenu.c32
isohdpfx.bin isolinux.cfg libcom32.c32 poweroff.c32 splash.png"

if [ ! $(type -p xorriso ) ]; then
	printerror "'libisoburn' not installed."
	exit 1
fi

if [ ! $(type -p mksquashfs ) ]; then
	printerror "'squashfs-tools' not installed."
	exit 1
fi

parseopt $@

if [ "$PRESET" ] && [ -f "$PRESET" ]; then
	. $PRESET
fi

OUTPUT=${OUTPUT:-venom-$(date +"%Y%m%d").iso}
PKG_CACHE=${PKG_CACHE:-$CWD/cache_packages}
SRC_CACHE=${SRC_CACHE:-$CWD/cache_sources}

if [ "$(echo ${OUTPUT##*.})" != "iso" ]; then
	printerror "output name should be .iso extension"
	exit 1
fi

trap "interrupted" SIGHUP SIGINT SIGQUIT SIGTERM

if [ $UID != 0 ]; then
	printerror "$(basename $0) need run as root."
	exit 3
fi

if [ -z $VENOM ]; then
	if [ ! -f $(basename $ROOTFSURL) ]; then
		printstep "Fetching $(basename $ROOTFSURL)..."
		fetch $ROOTFSURL || die "failed downloading $(basename $ROOTFSURL)"
	fi
	VENOM=$(basename $ROOTFSURL)
fi

case $VENOM in
	*.txz)	rm -fr $VENOMSRC
			mkdir -p $VENOMSRC
			cleanvenomsrc=1
			printstep "Extracting $VENOM..."
			tar xf $VENOM -C $VENOMSRC || die "failed extracting $VENOM";;
	*)		VENOMSRC=$VENOM;;
esac

rm -fr $WDIR
mkdir -p $WDIR

# prepare isolinux in working dir
printstep "Preparing isolinux..."
mkdir -p $WDIR/{filesystem,isolinux,boot}
for file in $isolinux_files; do
	cp $ISOLINUXDIR/$file $WDIR/isolinux
done
echo "$DISTRONAME" > $WDIR/isolinux/venomlive
[ -d virootfs ] && cp -aR virootfs $WDIR

# install pkgs
mountbind_cache
printstep "Updating ports..."
chroot_run scratch sync || die "failed updating ports"
printstep "Upgrading system..."
chroot_run scratch sysup -y --no-backup || die "failed system upgrade"
printstep "Installing requested packages..."
chroot_run scratch install $REQ_PKGS $ADD_PKGS $EXTRA_PKGS -y || die "failed install packages"

# run revdep
if [ "$REVDEP" = 1 ]; then
	chroot_run revdep -r -y || die "failed revdep process"
fi

# unmount binded cache
umountbind_cache

# copy kernel
printstep "Preparing kernel for iso..."
if [ $KERNEL_FILE ]; then
	cp $KERNEL_FILE $WDIR/boot/vmlinuz || die "failed copying kernel"
else
	cp $VENOMSRC/boot/vmlinuz-venom $WDIR/boot/vmlinuz || die "failed copying kernel"
fi

# generate initrd
printstep "Preparing initrd for iso..."
if [ $INITRD_FILE ]; then
	cp $INITRD_FILE $WDIR/boot/initrd || die "failed copying initrd"
else
	kernver=$(file $VENOMSRC/boot/vmlinuz-venom | cut -d ' ' -f9)
	chroot_run mkinitramfs -q -k $kernver -o /boot/initrd-venom.img || die "failed create initramfs"
	cp $VENOMSRC/boot/initrd-venom.img $WDIR/boot/initrd || die "failed copying initrd"
fi

# make sfs
printstep "Squashing root filesystem..."
mksquashfs $VENOMSRC $WDIR/filesystem/root.sfs \
		-b 1048576 -comp xz -Xdict-size 100% \
		-e $VENOMSRC/var/cache/scratchpkg/sources/* \
		-e $VENOMSRC/var/cache/scratchpkg/packages/* \
		-e $VENOMSRC/tmp/* || die "failed create squashed filesystem"

printstep "Creating iso ($OUTPUT)..."
rm -f $OUTPUT
xorriso -as mkisofs \
		-r -J -joliet-long \
		-l -cache-inodes \
		-isohybrid-mbr $CWD/isolinux/isohdpfx.bin \
		-partition_offset 16 \
		-volid "$LABEL" \
		-b isolinux/isolinux.bin \
		-c isolinux/boot.cat \
		-no-emul-boot \
		-boot-load-size 4 \
		-boot-info-table \
		-o $OUTPUT \
		$WDIR || die "failed create iso"
		
printstep "Generate md5sum..."
md5sum $OUTPUT > $OUTPUT.md5

printstep "Cleaning up..."
cleanup

exit 0
