#!/bin/bash -e

interrupted() {
	die "Abort by user."
}

cleanup() {
	[ "$cleanvenomsrc" = 1 ] && rm -fr $VENOMSRC
}

die() {
	[ "$@" ] && echo "ERROR: $@"
	umount_pseudofs
	umountbind_cache
	cleanup
	exit 1
}

chroot_run() {
	mount_pseudofs
	chroot $VENOMSRC $@
	umount_pseudofs
}

mount_pseudofs() {
	mount --bind /dev $VENOMSRC/dev
	mount -t devpts devpts $VENOMSRC/dev/pts -o gid=5,mode=620
	mount -t proc proc $VENOMSRC/proc
	mount -t sysfs sysfs $VENOMSRC/sys
	mount -t tmpfs tmpfs $VENOMSRC/run
}

umount_pseudofs() {
	umount $VENOMSRC/dev/pts &>/dev/null
	umount $VENOMSRC/dev &>/dev/null
	umount $VENOMSRC/run &>/dev/null
	umount $VENOMSRC/proc &>/dev/null
	umount $VENOMSRC/sys &>/dev/null
}

mountbind_cache() {
	# mount bind cachedir
	mkdir -p $SRC_CACHE $PKG_CACHE
	mount --bind $SRC_CACHE $VENOMSRC/var/cache/scratchpkg/sources
	mount --bind $PKG_CACHE $VENOMSRC/var/cache/scratchpkg/packages
}

umountbind_cache() {
	# umount binded cachedir
	umount $VENOMSRC/var/cache/scratchpkg/sources &>/dev/null
	umount $VENOMSRC/var/cache/scratchpkg/packages &>/dev/null
}

usage() {
	cat << EOF
Usage:
  $(basename $0) [options] <venom source>
  
Options:
  -p <path>           set packages cache directory
  -s <path>           set sources cache directory
  -P <pkg1 pkgN ...>  package to install into iso
  -o <name.iso>       output name for iso
  -h                  show this help msg
  
Note:
  'venom source' should be a rootfs directory or rootfs tarball image
  
EOF
}

checkinput() {
	if [ -z $1 ] || [[ $1 = -* ]]; then
		echo "this option need argument"
		exit 2
	fi
}

parseopt() {
	while [ "$1" ]; do
		case $1 in
			-p) checkinput $2
				PKG_CACHE=$2
				shift 2;;
			-s) checkinput $2
				SRC_CACHE=$2
				shift 2;;
			-o) checkinput $2
				OUTPUT=$2
				shift 2;;
			-P) checkinput $2
				while [ "$2" ]; do
					case $2 in
						-*) break ;;
						*) [ -z "$ADD_PKGS" ] && ADD_PKGS="$2" || ADD_PKGS="$ADD_PKGS $2"
					esac
					shift
				done
				shift ;;
			-h) usage; exit 0;;
			*)  VENOM=$1
				shift;;
		esac
	done
}

CWD=$PWD
VENOMSRC=/tmp/venomrootfs

selecteddir="bin dev home lib64 mnt proc run srv tmp var boot etc lib media opt root sbin sys usr"

parseopt $@

OUTPUT=${OUTPUT:-venom-$(date +"%Y%m%d").txz}
PKG_CACHE=${PKG_CACHE:-$CWD/cache_packages}
SRC_CACHE=${SRC_CACHE:-$CWD/cache_sources}

if [ "$(echo ${OUTPUT##*.})" != "txz" ]; then
	echo "output name should be .txz extension"
	exit 1
fi

trap "interrupted" SIGHUP SIGINT SIGQUIT SIGTERM

if [ $UID != 0 ]; then
	echo "$(basename $0) need run as root."
	exit 3
fi

if [ -z $VENOM ]; then
	echo "Venom source not define! Aborted."
	exit 1
else
	case $VENOM in
		*.txz)	rm -fr $VENOMSRC
				mkdir -p $VENOMSRC
				cleanvenomsrc=1
				echo "Extracting $VENOM..."
				tar xf $VENOM -C $VENOMSRC;;
		*)		VENOMSRC=$VENOM;;
	esac
fi

# install pkgs
mountbind_cache
chroot_run scratch sync || die
chroot_run scratch sysup --no-confirm --no-backup || die
chroot_run pkgbase linux scratchpkg dhcpcd rc sysklogd || die
#chroot_run scratch install $REQ_PKGS $ADD_PKGS $EXTRA_PKGS --no-confirm || die "failed install packages"
umountbind_cache

# generate initrd
#kernver=$(file $VENOMSRC/boot/vmlinuz-venom | cut -d ' ' -f9)
#chroot_run mkinitramfs -q -k $kernver -o /boot/initrd-venom.img || die "failed create initramfs"
#cp $VENOMSRC/boot/initrd-venom.img $WDIR/boot/initrd

# make rootfs
rm -f $OUTPUT
pushd $VENOMSRC >/dev/null

tar --exclude="var/cache/scratchpkg/packages/*" \
	--exclude="var/cache/scratchpkg/sources/*" \
	--exclude="*.spkgnew" \
	--exclude="tmp/*" \
	-cvJpf $CWD/$OUTPUT $selecteddir || die "Failed create rootfs image."

popd >/dev/null
		
cleanup

exit 0
