#!/bin/bash -e

interrupted() {
	die "Abort by user."
}

cleanup() {
	[ "$cleanvenomsrc" = 1 ] && rm -fr $VENOMSRC
}

die() {
	[ "$@" ] && printerror $@
	umount_pseudofs
	umountbind_cache
	cleanup
	exit 1
}

printstep() {
	echo -e "\e[0;36m::\e[0m $@"
}

printerror() {
	echo -e "\e[0;31mERROR:\e[0m $@"
}

chroot_run() {
	mount_pseudofs
	chroot $VENOMSRC $@
	umount_pseudofs
}

mount_pseudofs() {
	mount --bind /dev $VENOMSRC/dev
	mount -t devpts devpts $VENOMSRC/dev/pts -o gid=5,mode=620
	mount -t proc proc $VENOMSRC/proc
	mount -t sysfs sysfs $VENOMSRC/sys
	mount -t tmpfs tmpfs $VENOMSRC/run
}

umount_pseudofs() {
	umount $VENOMSRC/dev/pts &>/dev/null
	umount $VENOMSRC/dev &>/dev/null
	umount $VENOMSRC/run &>/dev/null
	umount $VENOMSRC/proc &>/dev/null
	umount $VENOMSRC/sys &>/dev/null
}

mountbind_cache() {
	# mount bind cachedir
	mkdir -p $SRC_CACHE $PKG_CACHE
	mount --bind $SRC_CACHE $VENOMSRC/var/cache/scratchpkg/sources
	mount --bind $PKG_CACHE $VENOMSRC/var/cache/scratchpkg/packages
}

umountbind_cache() {
	# umount binded cachedir
	umount $VENOMSRC/var/cache/scratchpkg/sources &>/dev/null
	umount $VENOMSRC/var/cache/scratchpkg/packages &>/dev/null
}

fetch() {
	local filename
	filename=$(basename $ROOTFSURL)
	rm -f $filename
	if [ -f $filename.part ]; then
		wget -c --output-document=$filename.part $ROOTFSURL
	else
		wget --output-document=$filename.part $ROOTFSURL
	fi
	if [ $? != 0 ]; then
		return 1
	else
		mv $filename.part $filename
	fi
}

usage() {
	cat << EOF
Usage:
  $(basename $0) [options] <venom source>
  
Options:
  -p <path>           set packages cache directory
  -s <path>           set sources cache directory
  -o <name.txz>       output name for rootfs
  -h                  show this help msg
  
Note:
  'venom source' should be a rootfs directory or rootfs tarball image
  if not define, it will download prebuilt one
  
EOF
}

checkinput() {
	if [ -z $1 ] || [[ $1 = -* ]]; then
		echo "this option need argument"
		exit 2
	fi
}

parseopt() {
	while [ "$1" ]; do
		case $1 in
			-p) checkinput $2
				PKG_CACHE=$2
				shift 2;;
			-s) checkinput $2
				SRC_CACHE=$2
				shift 2;;
			-o) checkinput $2
				OUTPUT=$2
				shift 2;;
			-P) checkinput $2
				while [ "$2" ]; do
					case $2 in
						-*) break ;;
						*) [ -z "$ADD_PKGS" ] && ADD_PKGS="$2" || ADD_PKGS="$ADD_PKGS $2"
					esac
					shift
				done
				shift ;;
			-h) usage; exit 0;;
			*)  VENOM=$1
				shift;;
		esac
	done
}

CWD=$PWD
VENOMSRC=/tmp/venomrootfs
ROOTFSURL="https://github.com/emmett1/venom/releases/download/rootfs/venom-rootfs.txz"

selecteddir="bin dev home lib64 mnt proc run srv tmp var boot etc lib media opt root sbin sys usr"

parseopt $@

OUTPUT=${OUTPUT:-venom-$(date +"%Y%m%d").txz}
PKG_CACHE=${PKG_CACHE:-$CWD/cache_packages}
SRC_CACHE=${SRC_CACHE:-$CWD/cache_sources}

if [ "$(echo ${OUTPUT##*.})" != "txz" ]; then
	printerror "output name should be .txz extension"
	exit 1
fi

trap "interrupted" SIGHUP SIGINT SIGQUIT SIGTERM

if [ $UID != 0 ]; then
	printerror "$(basename $0) need run as root."
	exit 3
fi

if [ -z $VENOM ]; then
	if [ ! -f $(basename $ROOTFSURL) ]; then
		printstep "Fetching $(basename $ROOTFSURL)..."
		fetch $ROOTFSURL || die "failed downloading $(basename $ROOTFSURL)"
	fi
	VENOM=$(basename $ROOTFSURL)
fi

case $VENOM in
	*.txz)	rm -fr $VENOMSRC
			mkdir -p $VENOMSRC
			cleanvenomsrc=1
			printstep "Extracting $VENOM..."
			tar xf $VENOM -C $VENOMSRC || die "failed extracting $VENOM";;
	*)		VENOMSRC=$VENOM;;
esac

# install pkgs
mountbind_cache
printstep "Updating ports..."
chroot_run scratch sync || die "failed updating ports"
printstep "Upgrading system..."
chroot_run scratch sysup --no-confirm --no-backup || die "failed system upgrade"
printstep "Strip down system to base..."
chroot_run pkgbase linux || die "failed remove packages..."
#chroot_run scratch install $REQ_PKGS $ADD_PKGS $EXTRA_PKGS --no-confirm || die "failed install packages"
umountbind_cache

# generate initrd
#kernver=$(file $VENOMSRC/boot/vmlinuz-venom | cut -d ' ' -f9)
#chroot_run mkinitramfs -q -k $kernver -o /boot/initrd-venom.img || die "failed create initramfs"
#cp $VENOMSRC/boot/initrd-venom.img $WDIR/boot/initrd

# make rootfs
printstep "Creating rootfs ($OUTPUT)"
rm -f $OUTPUT
pushd $VENOMSRC >/dev/null

tar --exclude="var/cache/scratchpkg/packages/*" \
	--exclude="var/cache/scratchpkg/sources/*" \
	--exclude="*.spkgnew" \
	--exclude="tmp/*" \
	-cvJpf $CWD/$OUTPUT $selecteddir || die "Failed create rootfs image."

popd >/dev/null
	
printstep "Cleaning up..."	
cleanup

exit 0
