#!/bin/bash

#
# script to update venom-installer
#

if [ $UID != 0 ]; then
	echo "ERROR: You need run as root to update venom-installer."
	exit 1
fi

if [[ ! $(ping -c 3 google.com 2>/dev/null) ]]; then
	echo "ERROR: Please check your internet connection."
	exit 1
fi

echo -n ":: Updating venom-installer..."
wget https://raw.githubusercontent.com/venomlinux/venomiso/master/virootfs/usr/sbin/venom-installer -qO /usr/sbin/venom-installer

if [ $? != 0 ]; then
	echo "ERROR: Failed fetch 'venom-installer' from 'https://raw.githubusercontent.com/venomlinux/venomiso/master/virootfs/usr/sbin/venom-installer'."
	exit 1
fi

chmod +x /usr/sbin/venom-installer

if [ $? != 0 ]; then
	echo "ERROR: Failed set executable for '/usr/sbin/venom-installer'."
	exit 1
fi

echo " done!"

exit 0
